name: HMM-364-Purple-Foxes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.96812
title: "Swifty's Side Project"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e15af'
    - '#d8d1d9'
    - '#272528'
    - '#452660'
    - '#baaca0'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
