name: HMM-364-Purple-Foxes
favicon: null
layout_spectrum: 0.54471
typography_spectrum: 0.96812
title: A Little Project from HMM-364.org
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e15af'
    - '#d8d1d9'
    - '#272528'
    - '#452660'
    - '#baaca0'
  brandStrength: 0.19170860527083278
  lightness: 0.9403462773188949
  saturation: 0.8521765291225165
  rhythmicContrast: 0.016697614220902324
purpose: []
