name: HMM-364-Purple-Foxes
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: "Swifty's Side Project"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e15af'
    - '#d8d1d9'
    - '#272528'
    - '#452660'
    - '#baaca0'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
